apiVersion: v2
name: events
description: Data Analysis event triggering
type: application

version: 0.1.2

dependencies:
  - name: argo-events
    alias: argoevents
    repository: https://argoproj.github.io/argo-helm
    version: 2.4.4
    condition: argo-events.enabled
