apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: default-queue
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: default-flavor
      resources:
      - name: cpu
        nominalQuota: 4
      - name: memory
        nominalQuota: 4Gi
  preemption:
    reclaimWithinCohort: Any
    withinClusterQueue: LowerPriority
