apiVersion: v2
name: secrets
description: Sealed secrets for the workflows platform
type: application

version: 0.0.7

dependencies:
  - name: common
    version: 2.23.0
    repository: oci://docker.io/bitnamicharts

