{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oauth
  namespace: workflows
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgBoEh41o1tKPnN0+gW959cAqPWUgaaFL6ZpCH4B9lhTyqRtKeQuN31cnJ2wRWSi6pzurdzcB0ZA3eLvQwFfCH6FW6ynSJGG0l22VvLFPI/cEavmcq7ri7vlYcHPeguZH5ac1QEc2kYa4XmhLlZsv7r9OXMjLD2W9Vo9E6W83Pr1wmnd4Bl5cT7KJRAlyZrMMT9YoQOiloPdh/XhrFvopaLwWCZCsSwIIEHPZmxxYz1Rzz3F4f6DXwRcCM2BUGmlh6JkqcwF+FivSQ+6Naswz7FriXRLpNnzXzRQHRWdJHB5oz6DdYE7CWaUzVAWK4vVxGXA+hmXJVxDAwx/HKRdVd3d+G4WWu9vgtVQM34TplDW1YlkXvH+2mXntNJjf9hGqfsmjMDYaAOjYiOuex+EruVzomoaBSHOJ/H84ZBYMkgRqqqXZt/IS1U0ctj/OyWLtAGm4WTXKs/S8m2t8eCmc4hqRxTamPksDroif1CztMsj8aMP/x3/QOCHPohu07+yuw00oCP0ju2iomDB0vfCwt+yU5WAVabRbo4RmFjPvyiz09Nb0aB+QiB3tW+k2wkU3plRxwlqs5aV7lK9fX7ENkmk1a7xzryBLu3U6bXYEmG5A3PLYieEWTfEN8N8wQyQFKO5PBFxLAY9Llh4l7YGWWJEVmsiHs3JR0FcafuuVUenjWMPHaGeveVGRvkuL6tksR5KAWrn8xSh2VFbJ3mn8T5KyyD2AuLgMlEhq1mYFk/01g==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oauth
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oauth
  namespace: workflows
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgAFVTQmYWBaQn6enJa7cfj+YTR6mE7uupoahi5yC5vuo3iMkRLfTvvqB3IMidOA2woDondInxVzqbPyr3LTrkjqW++ON3SxgBenxuN5p4KkoA5Plf0v4BvBkkBGK0Ati7RPVO0S0/RefZm8bucXkINaZ0uNxsrNmkpB3X3lq0fhsH8OAPhy9ocR8j0Ind1i3z7VPUnu+7vA5KsvlNWDtQlKYnJFIrjJYxXZy7p517NqI0odUJiDOixNrsk04p/rQtENbc+o++iKggtijdREMx17Yta8U9Fq0YLqeEgijCIO8Z8dh//riyuGZZTkP6M7p48NBlnupmaBmRiz2qF62tHfF15vmYZv5IFvGn9v+OmxNbCPc70wgSxBOwJBw8sN+oA0+O6pzVcNw++utaLqdNYgNb5YrbCFu6TPyljhKPHSGioZfZm8JtMgmSTTMUcAyruDcCOpNyLZ7GzgQt7GZhxWigrmgjGBG58Ot0k9esXXHixpxB6QOiFtqaR6tZQElZ+1ENHPcdrrIUKZ08wI3+x90e03v+BMKOIlWaiSfrDVOK1bJwxUJHnS/Oqebt2TFLvA8G0xGYCseCuH1iyG71kX0fruQM69ySSJlXMj6/bO5NEH2G9fpbrJELBGvQmOV302EPl/OHMo7bD5iYlE5HyOHlwTjYGueuU8KXIV0BxbgH/7m9eV5fFusDw9kdlx9NfcLv3GsJTpNgA8vP3FiUVyQzBFXsh9F5FRiSeRgsMlUw==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oauth
      namespace: workflows
    type: Opaque
{{ else }}
{{- end }}

