{{- if eq .Values.cluster "argus" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-passwords
  namespace: workflows
spec:
  encryptedData:
    password: AgANhuUeddILzy90b6IlUsYxkdEddMFMGDBEfe+rBxi8lPhh5kL+ippAiRpT1dTnE5OYK23j4ePCSPi6XEhRzR3qlTThCBAGEi16aknjNDbRzpZ7woUv0w9mlJe4WaDZ3KjtYMqWv4/d992t6bHBY3YJHHYx5i4DTp9wozTLfqPViI0GgbBDPjcFdnU5mY0y5R161YclQdAjQWZjezZZu34jDcMcY9+3aYGw8r+86dZihXfpTBV0krWdcgciUoILNoQdXOzzWIY/NcNeSBz65DdHRNwoo3/OTIpHKu7vnZZp/ltXLcB9MMQ6RdAC9SUupauxjH0jZgGgyERmBcRzX7uH2EBhYvzWLfsVL7TbnqRe69TdnsbGhVH37MHCHCKUCUXq8OUxMy8tlB/wlBpzn8jRqGapU+EsaC4Zo63/MBliCGEA7TKROddkSbD3MyDJ2tkYj86mr9M/Kl+Xy1BhjsP0uaZtFdn4R2Mex31LqbAi4o585X+jdox1VmDkh/3S6+CUTFiqo8nA9smBCjf/lIHDM/8UeWgWarfCCCbHXApcsPESc8IlYnr5VGcXWczLk3PCYL1av9gQdJOcu8axuFvTnev+9fzxRxxej0m6FiQ3NMyKND4CY70Rl4YpL1VSA5vCWlYuqeaGcE8vVutPb8Zrxq7SK+bzMNcIt4oBSeGKgMlr8js5HTI62NK3Zl2HDVUqDN3l8Td4DBx1rG5ba5s+Sh2xXttyRhA=
    repmgr-password: AgA5B9YCmaGaKHBdArNs1iulEYfTCHuqOXX1nlYGlgHI0n6HI/8y5ifBT4o8sJ6FsfXjrm8ryWTsbL3qUmBwqeG7ypyqKDyfOt9r38b+Djkp78X4Uskl8Ctu63zHZGU0SFDSWEJtSDU4pMAQ+JsZlGX+Yz2VQ4gScfiXcLAkwg4bJboJ8MZqbuIEQCCcdosn3+XsUVihBXyINvZdVhhtloESFZ9JiEGHhlddjHye+EcSvs3Q6vUwWQARL3kVjJA2ADN4K+xkGiJrRR4q2E2RCmtPqNTq+mMj1fX8EWibP+vtzwFN+uFDVMIkVKEdv8FUVWST+DDmfcvBvahLtu1jBIdJnBlg+kzTkuDRyBlYDmdaoPqNB3tS05I+JdJYZjhKMksRyNj0/LI302OiGbi06dyLc09+rh0JlwOgSsT/h9P9g3nkDB0/S6+xKESTWryvkNy6LBwUFPB0wsjzC3r/34/WgDCw7GStcRw69bFjQicjPePwpKTU6ZIDTQ7rIfjK/f0DcxHgG1k9V9OWe5UJTxM3JInZ8wlaH1/Ird5T2roIYaF1FOFAveWY13KRrOr3HAwVE2PfynGOnGwlkZjAtXO+hawdRR2v1DWAgE2A8lXb7KeCg16JLBkb3aVH0MTXtCqTMZii16vUjzt8nFERLC8K2IZ1jxXJkHDWhpxbBMmeHNoQ1b4PEQcxiqQ7S6xNvCUXliBSdSsYfuDqliUBo4cG7ouJCtUauN8=
  template:
    metadata:
      annotations:
        kubernetes.io/service-account.name: workflows-user
      name: postgres-passwords
      namespace: workflows
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-argo-workflows-password
  namespace: workflows
spec:
  encryptedData:
    password: AgBOY2wsugDA4KGrCPAsFRwXq4pnPrFW25NAi9O136b5hCjs/CJAWqcXFfmOnW6OKXCG/xUQrAnOzw/UGIXW7/YEACxm/KOGFVsGkvNvyGB0w1JPn1gRzPBZOXbYnkOwrdk6vPL8WQivAOk00sfk8k0+xw2uhuChNJOc4onbLzFwt1jffCPlRPgd8AXDY/e1OTB9B1uldJLp6Y3xsegEiWIeFrDsl+unrN6lp2Mxl9I989z4RmsvPqXRZaCTUkSHU6CdDR3WwvJBUpFJWCRBwclajStQ6X3YEZ/WFYx8GDLzTSYOP4LbxhPouMJa0MhTKN1HIhygxsfstDeNIIgD0hsaYn/hqSS1UbJDo25NMyJHV/cULF3uPIdSSmzU/WjLvvpcfySpEk6EntSVgOGH/RR+MwwT2/8Mcf1fTvCkOQXnmjLc9Iz+An/uJn4XDqpDzq0VwCYWcdpGIf2McX6sTKRbb2DL8/gT1Kpx48pZnbiXTFX8RZLDZaLoGLJq/dFod2tnhpEtuwTbXeqPQI+CKs3r32081bl3cmFeyxX3C1LqWPxbjLqwezYuEzogKzwExrtovwv/iQorYBbWBo6p17/OyDVQhKS8KE/yFp3pS3RbY+23wkQa19FX2RfAbZMX8ND0NsUj8xlgsd3edajiN8RqIy+2WqCmGkn1wbEggtc+ioPXnIcJKgwdCUFygQMi7rdZ0DgmHSCS8zXRxfvIhUaBVTkVU6u/9gw=
    username: AgBJ+NkWCl5RCXj5R/z1/52Ow8EMX/K0mW1Fxc7t3D7UgyAZ0RG6VYgi5ZBBhCxUUwlhVL6CADRGEGUx47aXFVoDZvtTNFRVha33f41uqUAzmia2Z0k2ABvO2hEXlIR8pXUCdKODpHRU4pWRVYZ5oq0U3vDbpDbXht/p+el5Nb3apbPoUxGoTi5zK0SA8BaL7EGlknFl66RmfC/jAouyNyRyiVsCNmYEwTUl3isZQ1IAZpItHtFV25t4JuL2qXWpWZld/xeUOOhu15zLmjJp1K4HiW9gPfs87++cC/l+z7JB+iCZDTd00hPjqrlFIXDvLGRgRFv5Df9FYjZ1WUNNEJtxJC12D0zEWodmXdbsx6fJSqBKHb38JpBQbixMD+wD4+83nsKRZ8AfByU5Teq7d1xRLvd3CR+YU2QXaWqhz6+tKd0Q7F6bhL8ezXjQAIpc4bhaeeWiRXKCgCz7F8KcW9cIZvCJYWTxVYeqq2HFFUKlk90QSIRYteqIwsgG90TzC53LN31rUMw6kLJvCGn6ouVCHKIyDeaD0GhpFSUbaKl8zQuFXneCJhNIJCwXnf+qg1bbIK8yiKfhEU6PxX4f9Pa+0cD/UoTdm7KhKsYnw9lWffszRc5XLJ0oGCLyn7NpyKg4ZNtJ2ThwxnQoJG0IcOHpGvQ1/U/FNeoKxzpWbn/7o+EaukChGYf9tVLEUcI48ggVAB6tKSzeDSk7/kr6Ig==
  template:
    metadata:
      name: postgres-argo-workflows-password
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-passwords
  namespace: workflows
spec:
  encryptedData:
    password: AgCD975klQIo4jCf3FWAlH5aszS+9Z6NH1pf2vS7v4FhXhgpcluoXv6YTcMPC5HJeH/sHHEEP391HhCSDOMaz04QssT3/E50GKFV7AJKdSuwYElt5qz0AzQVTdx2m5i+r/XzEOSAdQ7IghGx8h0pHNUC6uuU+9ByNBWYB1RtmOLGKir6la2TjQkogQz/JAK9GFjkw04XL6c678Swq8jS0KbrTzJYyVC1HVKVUNQGZ8N74ZiZaFz1tevpUINykrROYVhbNliuDVG7YCjKAFDWiQ+hpDxRzHjf7f5wJqlAsIgOZF/w/6t6vz+0tJoPZ2sqTftaZvc6VN0P+kTeXysQa4xfqKpsNbFWrvvjWQLzt25nM79KrDuDduUEcyX35gtBRIUx10gXCEb2SfiLvnYfg/MKTf/n00PBrWXi5h/bxWUKfg+Q330KMCha7iJVreUTk+sR+RIBs04mh+X2PR7EYCUBT474JZTidgN5tUxs4Lyd9q7dTxPklt4b0vzx5JOJPk55clWJe52u2O/49iYAnn0ZFlXqmW/qOzIGDENwdZxr8X80QtAtglhN7lkRaGIQ7zldaaiiEs0PsiAs0ITiO6L6plB71WOS5XiJg3hk+dcz1xZT+/OScHiOIZjFZ5AmTs+IW4EWIzNJ/kcVwe1Iz1pvK/AMvCGn2Hso9+IdBT/liheBP3eD09PPlyR6jyVMdtL+CF58UEAKE+qlUb6g5N+a/wo2helYJH1k25+kiZTPDQ==
    repmgr-password: AgCinRf4ivcMlpyJykho83biVnyqQfwh9pOldXhEmUi4S8Xr9IeKXJC9VP+SsrGRJ1PD6h6PYf3IlgYx8ulJh+ucN+CHp8JRFApUTRhDcdF9lkyWvzdQAYbQGAx/rKkLfyam7HIy9HrAAMTUvagMFKQyW4bCM8Beqdqd5CYSjzL2nLl8jc3HcetFMjHTLgt7zpNWadFw4gLnmRr3kkb6CY31E+7warT3XxhJkRAjp1dt5GJ2zLS/jL/RadTINA2FBuDYp5puw6gKps7Up6tv421v3vUKk1erNiNktaTFqC5G4LEXiHJ3gFnMg8eC6aXxxHTe2OVAcLxWm/aC61MGt3jKuJpODHuuGftfu5ZgYNv3TRcrEtS+CGnXA3RgCvfdfvagkatCw8K4tsSajPYpSV0fdmOmQ4ey/eLUhYi7gkR98E78oLwMSx0aTr4GG1EZhL1gYYLdhdUqXJztL+4OXKo+nEs1egVPJAVkTzQycR7FIUJwZMlU4kPi5zRIyzXQelzNuWVDUB6tT+XL/hIHrzlLGfGBQCQlgEZCP+yG6wFBL/nQN5m6eUaWI3nd6qHMS+Z6FvC9+JS+MqM+0GKuDITuWjx279jDUEvgLRwpcGfA1L4NIV1xa7dZWZU7/tYKFghcRBrpwxivITsCRXtxB9X5q2NIE/pULv/WuuwG6TuRrqjbUS+EN5kh/MHYcA2jHiPsDtueCOmhaTRCs3QKurhXBz1g12NauDFZ/0Z+gsM6oA==
  template:
    metadata:
      annotations:
        kubernetes.io/service-account.name: workflows-user
      name: postgres-passwords
      namespace: workflows
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-argo-workflows-password
  namespace: workflows
spec:
  encryptedData:
    password: AgA9cVoZp5aMY5mfwSumn9n7d6RHfFmc00VXaKSIkqUIbIYl0KNS18iEvBuRkcuVELfDWZfOO039ArUMRHM5031P58x7fRS2fOcWtlnuF833VPiyCtwG9IM3PdnkN3rVDQd3THpcPyuIuX0kBT/+pKa7wvPHqnPtgCLxObLUqzZCoWr6+WTw61GeU9inuSb63RNKziwfy7BLisjfbL3E3KW74xNXtLNYYhj5eB+omCuia1125CIZwfVzbpqAfFxwmJVUjktOvk9/Qnv7YclkmtPFFEClXdiA4fh/e+C+E3c7I0hz3WhPasHopLay7WSfsAylqrBdpFG73/w39l0/vaeMOEGRTd+0wacJAQm6DkkhGCzDkF0BrB0Loqyq/nnJ9JpKvG6ESrGOhXi35JUVsWf6I/mKsyrd9DzpShSiuUAdfngY+7VbT9vrCHMtXo7RHp+D905LvfxV0/fSU1Sd6ZdYcE0/VFWzv93nN1IISJYdwSxOUxzw5X/ngz2LIKxw1oUPjYitBgDJOn1DQh4R0NvNhdpKTb8dwc4oARzjB861rsRufgC8Yo+MArAAK0L9zXVzlmpJBxsxEskwtzxDmVQiawGxhqryD5LER8sRL6yYlDKdTia3dSDm0ZITiwRhAtNAidOUNM7Z74D9DoC7XzmnoN2ROh7m3Xo14FLWOMdEsnblCvN3EhRK8IozvXYDhFlQsajCJTM41muNpbBWZwgCCcAFahIZERs=
    username: AgAmj76ol4cIIQSIM2SqhCqa83EGqyTIhDPjIoWaB7v32DA9PwRoH5Foe7uiGW7I9evGTiidDVihGvaZg/BgDxFaKsCd74NGVZCczxXxR5Jkru2RsbSyCewFx5WY5OG6y60S0lw2mupxA/DuN63iDBD3d6uOtd+4038Ovmg3HJeVgTYMwQwPBlpCDJzZEiJvbc8fXTnnv8K6SGlOg0weBG/OfhyOF+MVL+W/pchllpHp0AkWDtu2eJwIhQcHghUoQX9pKmAz8TNnLadv0ChosfGJB/FbQdlB4C1POHEyvjuRxeD88GbBGNX47H8I5g6Q4qy3RZF5U2/YgCndhXOQf8ASsu0ZAa2eWpEXNcsOASRqNq8amhGU2uWQXoGtKXvDNGW8wdDv9t0EWWHcVXybndqfz4zaiSXR+1rJpAiMdd0GHDJcRTmQj2JllhQ1hID8SsjMtwgBTzCmeZRqjUchMS7HsL6/7NJY5MudST3knI2n5ZISvIO25Uw9aJ6pPnUZ0tNR244TYgqKHO5TNlOou6g/nESqEnR2Gk4yx6NNvADDcgmMZBYXIVJhM6hTH24d520vMJrMekyX8uIMVHVxyPkPEQJilYojzqGiWtPjvbpfF5jh6+gbJc2ddMnDq4MQvGPYumcM5IC0+pPAEdUvEjEKI4LAt5wPQNHEY+TqHbMsJF59/qnPW797uOV9hLb4+oXpw00XS9vllKyXazJsMw==
  template:
    metadata:
      name: postgres-argo-workflows-password
      namespace: workflows
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth-service-password
  namespace: workflows
spec:
  encryptedData:
    password: AgDHejDxPArV97Etg07L0oUlMDTIFlluz3cqYfMfJe/MBoPWLN8wxWq/Vpmy/0+LAW5aj9sIPnsXCE0Pfq4tXdr7sLdhNHOA0Efy2m5WLcoyTzbTU4/f/beXIGsabDFVvgEvIrEYIu2TOJj1mTLFmESWbYG4Z822oXdKEdmAE4Zvf8wmSkGLfOoFXYueNBaQ7N2BNIeA1+8pywuHMmoyeTOyxk6J743vRiPqEK940H+BT5bhuZz370FJVeXnKq+SBgsckqVZ42Rp7VW2qW1+j+tAku6AHcRhCxV0KLPjf08oQrzcY60blBvW4AUiwLrSghK88DfswBENQKtYlYO9nt5mV7ZaBD1dnSetCM867fRiSyTXXN0PJAXZjgAqkdQ5W8cBA5wImD0cF+wsZShZyVEO2qYGL5THrUATjHkSF2zGfhLSGHIlJlmsC527Yo2J0SovqjY4g3qTI8VxdugOax7yj/W8y2iwUxjokTvtwplIjM0nXNxwF7KqkbIOgxiW3IdtMyI7PQxTgO69jnch4odnzCgFToE7lOs/uVo1lNH+iU7a0o/o/5ksL8MqjX56zU1BYuGOtq+eGL9B3t7jnN91SkJzO9glRzuo15wRARKMdJ2Et2tqkfw6qQlCVnpvj8r4xApUnsMbvyrR6odP2jg5Sr2mgYnoN2krb6jjJwiBFeC3FZcJVctBUa60ZPpRiftXvUCpjhU4qMaABrk66k2xZZTD346wcMg=
    username: AgBRyZIlJrZnf0VtwQE1iqJbwxwcE9d638Ii21F75xCj1eVGne0t1oCysZpi9ZLOjhPYTWZADBW8VwYM6OchzMRcTAO3M4tsALsb2tsf8id9zMl7He1NIeprLeKr3hNQQ4Ktcf+CNrStr/f/b5Ei3Po8aA1Aq3VOiuBd+C+0P/nHJWcEGl0hbw3GEytjILHl7JwjMg40B6j2Diq3Z3o7fry17iJ98V0ta1kyQBpAZdlmPr+mSXpllpl915dhepE86//k9c+2ZIN7+WmLln4MYmznakbcZpiN5QAhuxnJO69G8wYcwSsJdI0B4fOy3iNMc/zNCWLbd3pgmz0h5hvumU1XZ42ftujTvhDb6eagBWPMWr7gguNSjWw6zwgtCPSVt+lzRBEu9MUBAY1TA3Zk5MvMXAYPTlix0vN6lPZweB2u1C/f/GqAV7BzTDMzxj58Fa/r/B1PEkOvgZygZ16TojXOQlkcMT7DfPf9Yf4YWL59i1RBzUvw2lgDB1glZ4GqMcxYHTfTR6j4feQJzmvVh2FgP0kthsxAXhO0a/sZ4EHfxVeN51PKA3BPuFdX56HLAkYvj2Osmuy+fVC8UGsDW9ik5fndzhaqxap/9qzLYUtU2AtEI3tPKvJhpM0QQvFockUgY6J31y1IivOo+gGGS1DCnRVnNDPHXETE2DBidSwBSThTiuV8+7LMrCyoAvaFEBFhENcrbtX5Eb8=
  template:
    metadata:
      labels:
        argocd.argoproj.io/instance: workflows
      name: postgres-auth-service-password
      namespace: workflows
    type: Opaque
{{ else }}
{{- end }}
