{{- if eq .Values.cluster "argus" }}

{{- else if eq .Values.cluster "pollux" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-passwords
  namespace: workflows
spec:
  encryptedData:
    password: AgCD975klQIo4jCf3FWAlH5aszS+9Z6NH1pf2vS7v4FhXhgpcluoXv6YTcMPC5HJeH/sHHEEP391HhCSDOMaz04QssT3/E50GKFV7AJKdSuwYElt5qz0AzQVTdx2m5i+r/XzEOSAdQ7IghGx8h0pHNUC6uuU+9ByNBWYB1RtmOLGKir6la2TjQkogQz/JAK9GFjkw04XL6c678Swq8jS0KbrTzJYyVC1HVKVUNQGZ8N74ZiZaFz1tevpUINykrROYVhbNliuDVG7YCjKAFDWiQ+hpDxRzHjf7f5wJqlAsIgOZF/w/6t6vz+0tJoPZ2sqTftaZvc6VN0P+kTeXysQa4xfqKpsNbFWrvvjWQLzt25nM79KrDuDduUEcyX35gtBRIUx10gXCEb2SfiLvnYfg/MKTf/n00PBrWXi5h/bxWUKfg+Q330KMCha7iJVreUTk+sR+RIBs04mh+X2PR7EYCUBT474JZTidgN5tUxs4Lyd9q7dTxPklt4b0vzx5JOJPk55clWJe52u2O/49iYAnn0ZFlXqmW/qOzIGDENwdZxr8X80QtAtglhN7lkRaGIQ7zldaaiiEs0PsiAs0ITiO6L6plB71WOS5XiJg3hk+dcz1xZT+/OScHiOIZjFZ5AmTs+IW4EWIzNJ/kcVwe1Iz1pvK/AMvCGn2Hso9+IdBT/liheBP3eD09PPlyR6jyVMdtL+CF58UEAKE+qlUb6g5N+a/wo2helYJH1k25+kiZTPDQ==
    repmgr-password: AgCinRf4ivcMlpyJykho83biVnyqQfwh9pOldXhEmUi4S8Xr9IeKXJC9VP+SsrGRJ1PD6h6PYf3IlgYx8ulJh+ucN+CHp8JRFApUTRhDcdF9lkyWvzdQAYbQGAx/rKkLfyam7HIy9HrAAMTUvagMFKQyW4bCM8Beqdqd5CYSjzL2nLl8jc3HcetFMjHTLgt7zpNWadFw4gLnmRr3kkb6CY31E+7warT3XxhJkRAjp1dt5GJ2zLS/jL/RadTINA2FBuDYp5puw6gKps7Up6tv421v3vUKk1erNiNktaTFqC5G4LEXiHJ3gFnMg8eC6aXxxHTe2OVAcLxWm/aC61MGt3jKuJpODHuuGftfu5ZgYNv3TRcrEtS+CGnXA3RgCvfdfvagkatCw8K4tsSajPYpSV0fdmOmQ4ey/eLUhYi7gkR98E78oLwMSx0aTr4GG1EZhL1gYYLdhdUqXJztL+4OXKo+nEs1egVPJAVkTzQycR7FIUJwZMlU4kPi5zRIyzXQelzNuWVDUB6tT+XL/hIHrzlLGfGBQCQlgEZCP+yG6wFBL/nQN5m6eUaWI3nd6qHMS+Z6FvC9+JS+MqM+0GKuDITuWjx279jDUEvgLRwpcGfA1L4NIV1xa7dZWZU7/tYKFghcRBrpwxivITsCRXtxB9X5q2NIE/pULv/WuuwG6TuRrqjbUS+EN5kh/MHYcA2jHiPsDtueCOmhaTRCs3QKurhXBz1g12NauDFZ/0Z+gsM6oA==
  template:
    metadata:
      annotations:
        kubernetes.io/service-account.name: workflows-user
      name: postgres-passwords
      namespace: workflows
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-application-passwords
  namespace: workflows
spec:
  encryptedData:
    passwords: AgBiNZgsZ39RCLs+FE3Wn0jQfc+Tqb5icWE/6y/nEsYcjEinkndsjpDDMmWYfhvoa1JWh78qodA9ZfRFQN2k0KWf68HnXQ5mbFYPMlnvxtBRwvuXByI5Al7buq0yfFvvTjoaaTPkUI6jnrC078MSyvuOJWepVOYTx7GQgxlR8puPbFSPp/98T8i2BrXLMjfu1BmhRHfL5wtbjHTGjJeYHdLCttPPrnRl3f2uWxAfTRo3BOQCyBBexFut4Hhehqq2CmTDB33U0uURjZnUzqYF51txmaOVK5sQSm5eous3V8BnIVNRcNdu1QFqDH+2EKt0OMtTVsb6tW56o0y4vbgbAJpgg5AM5STWvQUE0Y4KqNFGB0IYUq40sh+D+mXCLsgSk3EL1uMtp89tR6fKBDa2JVFdHNy0bgSL6dp6ggj2vD5x965Jl3QTFI/3BSuWiDnVBpJBS5t8pUOr6YjWhxm/L0nhzZGf/duFVYs1VBFKypX7lt7Y1nqD/hEkxKrGNVQ38Gr5+pme4RHM08SdNPR1wipgsEpTOHFYoP8Si48odzFen3YUMoDt2SFsGuXiEo4WW4fQAHcy9rqo5cwphQeBYPUMmVGdZg62UDwL1Kzvtc3hz2rXixEWoiTIbxYG2rcVp6C+uiZEEXRIdQnP42iiAf1tEu/8TsNNPTz+EVe+K1qWRzoJb0nhFkLXcW4mFaz9p0hcxh3uC0omanVxDnOy1tAfiS/TOpnFijk=
    usernames: AgC8xVjQMgqzhGndrYhqISDXJOnkLZoWNXt+6pvljZiruTam+7I+FsWgpt59hWMUhjfqRFr6IIijf+A8NiaEI2/6SHKZCRX1v0uJ/V2bHfpI05taFn51kKeOe16o1ozWwjj99Nzfweyp775m10M1zMGajWrnC7NtKCbW/wuukufLulY2ogLaW9ehNy//BUPMzLUe6x66Xnlwam3jp02zZoNAFh0v5lro3ZYvocKFrRoNgVsZJFb0KaBqn9QIf36O+PN4HQ2iy7QX2PVsMyGZxai1TdKpdeh/pVuGDMSNodj+X9bRxOfzAi0U2XTc5rmih2vQ7Eu8dLgHJfmjcSK8hB413rb8XtKI1ucJjfrRW6DTjqrJPszbQP4yJCYAwF0gBi4kAO4C3DhSEfWFueYGGkBTQX8F82ulsMFjkTIdKCFxhYGxJPdLIFGOAvXn8Yr2oilJm1PhGnM/pihf6x8nT4Ilsyd97oIQWVmmqxmXSTSWalK7EKGl6DeLmIEV+d1z0qdilvxr2B8nl8Cx+LZlv7YHQyHqcg0/ARw1tSTkYc1AyWLtoUK5XaktDIdx2tV85yEKWQbKpKIYT0LLZmSddta+GJsxQaioK2vb5XjnlBMMAtPG/YLdm33QWj291VEX460GeY5NLSuIbSxAIlhVhN2QPh7Y10VVd5GGyp7h7MggD3Ptz4JE7WfUm5R6+zI8UK8owzR+MJE7V8qLGxX9XQ==
  template:
    metadata:
      name: postgres-application-passwords
      namespace: workflows
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-application-passwords
  namespace: workflows
spec:
  encryptedData:
    passwords: AgC9QwtIoYwQ/KgnuEcXh/SJwST61+evmyIHd8gtZVKViPEPmflRVuuZ3e4wvgTlhAjOcZNL8AFEth2EV75pJA1BvVhl4/o4FD2mtXrK6nI/bX7KQ1MBmuQ0JeM/NCGUiC8y4W6WeaIw7yOQPgiKRlmqmNbInVP6pyYsWRNAI9UnVVAUvefvx5DGkJ+woEe9NKj3DpIKJ9BYLEySF2OKjO4PUBnCeEdkYIU+SYQ/rZjxevrA7cId9SiOfW8WUJB4dwZS+B3wRR9uS6pas1DlejomQv3QruIBNOsnsJj2ojkkWpZCIaIWDsROGSJy+HOl/u5vKjGERdmVCd/F21bX+vVy8sFU6sbR1h6cN2AzEB8LADmd++iqI0smeP1BUIPnV1Yhs+nXOlGuxWeO0CxGqn0Pi9SBSao2Lz4txAmfU7ZPnnE2NT3Pxp5IzEPKpskLWC6lzgRc/2/5JQZ81BJXMvaK64xqirAVJZDVuDNEzl6JTfAzK5P5hREsge6fOo8iupxRo/ESa7kCzlCBiNoR4hvaIZmvCqtbKhUtf0Hb1HdxGFU6TMgU6KQlz/m0xvQr77XQtZ9OAVbCnNl8YcNoN0QHHGemBjVeoOSb892y+zN+4uAtOaWyaYV/90oisH6fsao8vxA4dNL77dXzLt3I0guF1h0jAwBykRj8Xly9WJ1v1MI6AzN1eNWBaJJbJQqM5tXX9JZ8UVtAHpxOOFIKDXm4NMpTbFEcGpE=
    usernames: AgBNaSYptjeYMUcQWA/B4rgEdUhB/4w3Lbw4WC9CiYbm4pc2sLTw2Tz7aytAK5vNWIAh13j3ZAq0CjMREJ6uu55JxhsK8YGus1rV8l8iqt4rGLcW9lbqA0Sz6wV7SCLqbdGIgUmILiNHPWKBhoBdyWiafgni8II33DY4AMtgt//+B5DVp8ttO3PfT5MIzvmWbzkGz/OC0BuRhrfefEKg6y9DcDDseeVli6hRAXee+rJ0DLXDzrwkWWzI5wRb0ndsZPltLYz8BgLW7+aHshU0HRl5iNU/A8VrvN3600uWDY48oReMqytkyvbP08JcXhwA/fcczqZiufsTZvwd/TFrd6L2h1dbO45O7aVahfOasY9AGj/kdBpRp+4jVqr/BfIJu2hFFqB6sCiCRck/7FUtx6R1xk87r1qTmcfTso9Bj8/XL99hIDwObTRC2cWQw4oLbwLEdzirjpPnHc3sDlnYDUQy0PpX7KRsJaZkqvLO+WhnmIuzFahWzCNTHTS5DIM16xVncNdx54ZQU1iUBuNcFrJuvVVVvfgXYqv8DS2MpUc4wn036ZWZILL9UjHv9xLtGeykfflFlnGJpa6SQRuJUISrTr0/Dz+aKimzQxraqLXzbpcO5i3n4gLwA+TOFURxaywN5ip5Ic4dnkut4MCwcDbbNSOSuPj7gSf6ElncDXuxWOQ8wDe9m6p8zBvRP0sE7fX7bEtkM9QwxJuk9Tcz5g==
  template:
    metadata:
      name: postgres-application-passwords
      namespace: workflows
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-argo-workflows-password
  namespace: workflows
spec:
  encryptedData:
    password: AgA9cVoZp5aMY5mfwSumn9n7d6RHfFmc00VXaKSIkqUIbIYl0KNS18iEvBuRkcuVELfDWZfOO039ArUMRHM5031P58x7fRS2fOcWtlnuF833VPiyCtwG9IM3PdnkN3rVDQd3THpcPyuIuX0kBT/+pKa7wvPHqnPtgCLxObLUqzZCoWr6+WTw61GeU9inuSb63RNKziwfy7BLisjfbL3E3KW74xNXtLNYYhj5eB+omCuia1125CIZwfVzbpqAfFxwmJVUjktOvk9/Qnv7YclkmtPFFEClXdiA4fh/e+C+E3c7I0hz3WhPasHopLay7WSfsAylqrBdpFG73/w39l0/vaeMOEGRTd+0wacJAQm6DkkhGCzDkF0BrB0Loqyq/nnJ9JpKvG6ESrGOhXi35JUVsWf6I/mKsyrd9DzpShSiuUAdfngY+7VbT9vrCHMtXo7RHp+D905LvfxV0/fSU1Sd6ZdYcE0/VFWzv93nN1IISJYdwSxOUxzw5X/ngz2LIKxw1oUPjYitBgDJOn1DQh4R0NvNhdpKTb8dwc4oARzjB861rsRufgC8Yo+MArAAK0L9zXVzlmpJBxsxEskwtzxDmVQiawGxhqryD5LER8sRL6yYlDKdTia3dSDm0ZITiwRhAtNAidOUNM7Z74D9DoC7XzmnoN2ROh7m3Xo14FLWOMdEsnblCvN3EhRK8IozvXYDhFlQsajCJTM41muNpbBWZwgCCcAFahIZERs=
    username: AgAmj76ol4cIIQSIM2SqhCqa83EGqyTIhDPjIoWaB7v32DA9PwRoH5Foe7uiGW7I9evGTiidDVihGvaZg/BgDxFaKsCd74NGVZCczxXxR5Jkru2RsbSyCewFx5WY5OG6y60S0lw2mupxA/DuN63iDBD3d6uOtd+4038Ovmg3HJeVgTYMwQwPBlpCDJzZEiJvbc8fXTnnv8K6SGlOg0weBG/OfhyOF+MVL+W/pchllpHp0AkWDtu2eJwIhQcHghUoQX9pKmAz8TNnLadv0ChosfGJB/FbQdlB4C1POHEyvjuRxeD88GbBGNX47H8I5g6Q4qy3RZF5U2/YgCndhXOQf8ASsu0ZAa2eWpEXNcsOASRqNq8amhGU2uWQXoGtKXvDNGW8wdDv9t0EWWHcVXybndqfz4zaiSXR+1rJpAiMdd0GHDJcRTmQj2JllhQ1hID8SsjMtwgBTzCmeZRqjUchMS7HsL6/7NJY5MudST3knI2n5ZISvIO25Uw9aJ6pPnUZ0tNR244TYgqKHO5TNlOou6g/nESqEnR2Gk4yx6NNvADDcgmMZBYXIVJhM6hTH24d520vMJrMekyX8uIMVHVxyPkPEQJilYojzqGiWtPjvbpfF5jh6+gbJc2ddMnDq4MQvGPYumcM5IC0+pPAEdUvEjEKI4LAt5wPQNHEY+TqHbMsJF59/qnPW797uOV9hLb4+oXpw00XS9vllKyXazJsMw==
  template:
    metadata:
      name: postgres-argo-workflows-password
      namespace: workflows
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-initdb-script
  namespace: workflows
spec:
  encryptedData:
    init.sql: AgCMAUcfIwMH/y8FT+D0BXHm1mi/nvns0v4Shcn0Wq9Jg2wYh2SqSd2nFMU4pNZuONu/HEwiAtGQHy3Ev7bw971itFoDRSsAUpV16wdYGF7ic30D9NWFuvmjjqhIdx/SeT+MplRKSLIKvoyCrNEjra9xNdVoOi3cm0nT4w9UChEre4SfJMiMLZQX2tmfQTKASdJsx5XvV1YhIftb9ZWKbjfYDRCxLOI/mTV6aMluGEaHkQSH9/m24asuyax6gcZOpzLpIKKivLhj8NMBWAzY2YUFqxrZ/D6W6Ycr/iMhogHr2vnCCSWM8xlNPf6XBqqfipCn9URdCtC9glSnppXJpldB+m9iorTluvNQc/pro524VIWA/ANs92WqZqSVHt4b9E9gTX5FVeEYI4HCar/jAHK2FqWWaBXwAq54UfhTAQaJO/WbCUyzWHc+VAZld+RhxXpv+WKJjlq4qHREiDCUIYfRLPBM0+eQLQeNdG35LIFkIRYVQosClzyV7HlvFLqx3lUOi6zEYq3p4d9AlVsI78PjYrORlKnIhYWbV4kTnxfFaZvu9NO1toVnQFhwDavtBjI2iN+0ndpE4GLHc3TrKB7fLgh1vMJE5ZfbVTQqxihePNYyfFLsaCINu2bxR/32qYKVzH+4B/jpvv98Q1EcKPOvPh1t6eBgP1z10JNDEN3fzTjoHMb9kVxHfJHNjS8/gONdr1R8FN0OFXy9ZTrTP17rw7m1nkVAvkFiW0fw3z+bj9EP/iWCfmMsDqDRAEsecVK0TaQKX66EYXuI+/Vtfoi1+K+reVFCV0vB4ip1h9HfjWuSisx8swgrnA52BDpYcJ9YZV0DPwWPjReBlLiY6cOtlkuV8R15So+L
  template:
    metadata:
      name: postgres-initdb-script
      namespace: workflows
    type: Opaque
{{ else }}
{{- end }}