{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-artifact
  namespace: workflows
spec:
  encryptedData:
    access-key: AgAU8kmvzjfmGr4utduZDxxix4uhzkJY/WHGiIvWFne56TcTszMl4ZWqOnPMR5YQ+Ku4vQ2/7JvV18rwbxd88pNRmn9MFHQrZ/mJStTfgvscfRkcCy64XjCbtT8NOEb9W1rwjxNRB4k2nYOBR//b2uF6ie8bMfZVzrdCPq4mrrsQHhcHoj805rAWuA7CQre7GFW0WB6ME0T6Th9O+eIXLufTsWzPwyv5YK09k+73dwWCwClzkSM205JY1M+rLultzPfZMVhIXHwiJXGZqWhmgfLxX7kf6Ao6N7QAaHk3uUubWluOeAsLEngcuCPRRex/PM0eD3TQBnjC14vyFIQy44JxMfNB8n/uA0h73mqbmEGsOsXKpDu2SLv2hXNeM/epH1WxnGoO0h0RL54XXUtF6uWKYsUxRmHqWKBlLrFPJRugmJTsci4uRXifFR6LnteSU6JW2yWx58HciFG9Zf6Zz16dMRypNWGhaEu4hSM9K/gaRYFtc7LXankInAlYT6mkl/pWIhjRwGDaCrpsmVSTHnl6Oe//MaFQA7AbmtiJJMn3v39/jLUXXd5PV9uKgk8dffR3ZbJPr+kfdhbfyUW8ZcvydGQnVM3F++6dthAEIJV/6ZK+zhCAiQpi4sFiYjwY/USpRv7Sua3skDU9OzIZmOrkT/9UMOU/Sx9upcKAvyn4rzhhtSLtA+rFqunqVBIEJGt3S0tcL/CabH0gHmScm+G0HrqkFw==
    secret-key: AgCd5/JzYnBg4vno2OQKQQ6vuprJOV0D/4xUAjCKA0DCATiwupjjVmb5qczgpCV1RpybajQZ0Th3CUsQt+dIvjXILpYNNoY7eToiZu8ahanZ7oXRhL7K+I1s9r0jXGn4LwK1OTqIVPc4G09AmwOvD94t8VXEXBleUGbOaoKLHAD9gHg22eJO96QAsQIlMYlQ5zPqUUiyfcdQHcClCYUd0iv0xr1PU7Fki0bhihpBNU/eyWHoyFXrFecNwoJtUSiJbNkwPTO66auWAXdBYXZuBQdUrc4wiadVel1lA28aoQglRTOCcfydspRdGN8svjJEkJkECeSEsf6HxAxccRRVW20ocm+eKOzSTZh87oOZ6uAiSS2EzYpjfUdM768KK0M0eZOzeYZByAp0oQ/QI4AhI0IZ+PboncjHxNSmwSZQmBOch5ulrhL9VJHxSxM98yETbbFkqiXh9zrKCiGk6OMOFaWcGYIBbr1Bbn+tnVzyHyE0JcC5ngQ5BKen0h7X4+dPIFODp/gx34D452ijtWoDSUMqZYNHsTs07O6GeMMBJUBYCfZ2QBkQVofIG+pgG/wKSQOBsHSUggH530zjXOk5h1FFGCQYV3oQdIJjouUz6o5384GDcCn0tPXiHVKFrQFhKLGsikh2fKvlzwrGf6k+yc8aH9zQVRcvRi6vYfxwzeytjQadF7UIYaUeITRco3v/Vdu5jgRBUjMMyYvJLIx+KHO1OcYE4LbwqAa0Oa58uKbESiqJ7VacQe0r
  template:
    metadata:
      name: s3-artifact
      namespace: workflows
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-artifact
  namespace: workflows
spec:
  encryptedData:
    access-key: AgDQpiw7ypcYPfPPTIz5NFtxmJgA5oY0Dmq6OLA+/m/iceqqmjA/TGWuJ8enhXaK1h4jCAIiXPLvA+BtDdhvEDbXet9RS71BEl61iukrwWhuQ+sLjR6uzxDhvIGXjmbWWsXA13dtw3NfK4LKnEw3tBF90Z1f7OK/nDRLG2/5Fs3alJDxYFRU03eqtdNAVihP7TnQV9g3MohnITAnjQejdYpWWrE3v34rT3eX0B+nq+r2KXNN8SzIw0RP7Nro+d1D9wXuo/UkERUfXfBzAApfkrMSoZQVSod+SEgNv6/07Pyh7pqomXHgI5wLQn/4F6gp69cbVQzxUd3F5eF6/lBkDZ2VGzORnq/MHQQJcqu9f7gDtkIhy7YkVq7cmt9Bz7H1iQ3ektnS1o8ZFxEYfVWMkCpLs1L7AT160518797s3WSNaZl0356VyHlkEqc/PijyXRkB633c1echnJrEw1g8eIg9978sW9xSAeu8CWABxlIjgOBi1s13M9UKVFUZaU9+gHwpY4QTp+j6ojJehpQfdSY93wmLBm0NwcTMaBZ+M1axqYKSCka/jgY2uoqQ0+FbYu+OJpE6lPKK2/DhxaG6WmeufT86IutwiPxVowv4VDxl27oLktp16s4hMFPcMIGU0gSBXU9xWFXuGTC6lrPyiw7RQByr/gEHSUOW7nn3R814S4cp4OkhN+2o8yFMDPvKbzUe+x9Jer6BayJPx5g/x/R2gGH2yw==
    secret-key: AgAch6rzR/RPJUQM3GRY/qdNR60fzjkbwAizwWM9qHaAy3e0hffh/UVpvZ4eJnn4bu5E8BynA6dz4pidDLcRQIhwxWZRwdFFc7SWVJtoDQEndepQqtqKE5FZOnlbrZ8p3N0yV+vU504BKvssVaTOl+6Fp09a7yMahfqlMdXlx4+jmJQbE940QR/tgc47PEs+nANdsoIiPSYY5cj2X3DkDQFJaOrTwG9Y5OfRPa028ADyFyzLbfW3OSkLvTbZaH1gciA0V5e5kS2KyTET6cFX3jXEL5ydGe9Dse/GvAfq0onnZVcQyUHBZFXs0O4OMfsqMcy/djboblXWdzi8QUEYpXXKvp929s4JjnzZgIBS253bTogTbZJ6SDoq+gcKm7RHRtt2iIszS/WndB/wi0/SBPnTEJuT4nbusCHOseBB/3hXoFcNLXs764cHRYVhfYH3GoMEU8bxDOBw6glireY19qOOqrWA0kbUdl/BRHIpvLDkRylfjkIuL7C7EMVt8rWakwbj8HYMNzgTUMmUJ6mhOzOZ1nm4E88/9VSB8XW9VgWKhHzG5pYWjkuzfNWnL8yUr+RL3SwweMeIL1NAaD332brr+6ivQNRbP3bBqBBknZOz5ZNaS2bhEIGBbk1Z4f+VBKvD66adjXI8gB5i6XWoEnxZ1kKwNP4SrOMrQUt67Cpae7pKpbQOo8zblxk3h3cpndsDeuPLWfxz3Q/bYOgOZWy1uarEAsB/1ZrXXO6uTAZp8cg6llAT2f08
  template:
    metadata:
      name: s3-artifact
      namespace: workflows
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-artifact
  namespace: workflows
type: Opaque
data:
  access-key: dXNlcm5hbWU=
  secret-key: cGFzc3dvcmQ=
{{- end }}

