apiVersion: v2
name: sessionspaces
description: Namespace controller for creating session namespaces
type: application
version: 0.3.18
appVersion: 0.1.3
dependencies:
  - name: common
    version: 2.23.0
    repository: oci://docker.io/bitnamicharts
  - name: database
    version: 0.1.0
    repository: file://./charts/database
