{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-oauth
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    client-id: AgCVJCtHmUdZ2/sJSXB/dYaaPeCAxLdrXsTh3uJDK3zpqQPGlFMaonm+zgzcUgN5m2Ou0phxI+a/XycrOCw132ZRhVtgJm6PDpsmBXl0DTqng/37I7BeDmM7FxXbOo0WWSgBmqjC4bU/xXs8G0IbWl+n5pKw0BYplzaddzeqj5fsrDxswqfI+J1BBrwLVp6uNjnNEc2Nwyyc2KhY051RauX/F00Zgyx4rsYpDq8ulPC8lEa21W3/9bvyEALcrToBp5Su37YVizoF2bSTAzDpfk7xm9A0rHqqG29y/Oq215V9H8pCo/ocaRaWyOzs5s3JmpLtahDQFvToWat4+Scto/fhPVLyOX2xZE0MZ6dR7jWDxJiu2/RQLX7LM5iQ06d2JDFlkBZRidNJKBrx+h47zNeGd5XjDvfeaX0nCGKXYlaaxhdZ5cLHHF55KszaDgtnBHYAg/I3MUnPp98JPYzy96YUSzX66AEIQpH/XTeFbFQ9kHUAt1ZQbOfEzLXc1hO6tLFpxKAmcxdVbEzLPPfnRBJQ9JTxmXevoUeytCJD1XdhueMP4YBoWVAvThZDDW5Z9NSAgb7ozgPlRmtzAlUevVOIiOzAkGQUbnOOEXx7r6X2tWDnQp11kRSKtpbZnauu8GyUUnGMM7Evh3XZCHTpcGov8UF3b4dMEQai2v/9puFMsk7kyYCQOC5xYYDnvIo0hHI0XR24XoS2Ln8NcrSUlPgYzQ==
    client-secret: AgBM9XkD4SGqQHKL427bySL2iywfzo24h7OC7lRF/hIR97CybX/QO/OXqFXTrDjbzDNcOzLXuHFfgL6LcTPVrHsox/rQhwvEoybmjCNJK1rQJdMmmtL+RG2v5+9VD5po7+mKRnkottB/lBcCzgIeqBPznmnhr8GGctcH5QtQfBtJYSGAk8vYKnF3YwacGz50LvFHzBrt2sMtC7ustOcuijAvPHZJOqt+dC5dsy4c346kWzRpyV9UoZMzDBujycrA/ukv6C5KTx64BgYXp3i9qXHlB6GRaIpZ/p7r8jcFzenTwK8cfijl4+GEQEceS3NKECnKCympSyiiH2gxH4ap4JVRe7lalwxVn4HCxAIo6dIvwA/Lvh7h/89npIAI7cLKgv1aqJgvEBZz9i1948/7mEO4zbM+h8rMtGSNiyvWriScGJ+BFfVPCY0QaGphf+kCAtfHholEERqkfOXu3Py8e42drpgwXCJf4OiE4VM/URdHtSug+Cv5k2EvVcK5FKaHVu6ivaUzk47QsdxssICIg5bwqDoOcHUdPED7ylfA5BtIMjRTDxd4RLr/2gaPzzwEp6/wb8E/AYOR3Nq0cHHj4vViE1R8UEpofRXyoyGNV2Xrt04ci08HYb/3+twu6rwrJ9NHOPMSpWjbBbwkVRJpNWkZdtCj+oO0sc9rK/9N+Kn8esUhjXFJJ9LVnWorlSgQi/KtA4jSBc2RJp5PvIsS8a2TdkAZJGxlQZMJogUpRKz/wA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-oauth
      namespace: {{ .Release.Namespace }}
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    client-id: AgAZtZSY6p7+DgcrpquiQrk7+MrbvPNGGBb6oy58dftYo7exdsY6V8AvZTEpuEAmspC9NLt330MDyDXLYFX99OlLLlukJUuyx8cA5mx1l9sC72qDCRok2Zi4Y7K9gHwEXyPI327EPV7aGwZjtT0Cauz4xP4sRs0zpoPcbu2aseqf6tWR6KtXOO2zylC3xZwTN74mQRSpsePXgPhKjl+rdVcn7f6S0lDXez4EfaTpAG2HNTjBk/8Oh1066kNgUhEHIidce4v2eLHr15bmShrggkqaZHxDVz9lVGXo5GQcqpxjN92XOfESdI9hoSpvQ2tqFqZemK84SllOOp9EiG0jXr+GUuJ7E5LR+81XR63N/AqyxmWv3gHKSwwsvsC4GBc7hIFKU25hZV0ZVvZyo+ip9s0s0EJsGvIoZO843rFinGbQ428Q8O/IqhdtNQ9zJFPWmMb5QbVuiY8LuHg4wRig9xN/s+TSY7I+lS6IeWnDzb2xiyVJtHLHZ0LMR9pRDUryv+glmrUoMGyeXdGcvlIJbuSkMxttXaj+gPeKm+cTBkrhg6ageR5MYO4ZwvPhhtFJp/fm+ffZ69kieQr50sDOJlv7LePu/kDQ0NHKN3D1VpyiCtZMzAjCMr7ZM9kYjg8/jcLnuVL/1FriOWPQ9+v8Gt3XRFO3/c5CusAH3ZtlRrwUXa77zxEjGBeaj3IyxtkHTMtIfGyNoY5FKwzFNt0u4yr0DqRFwjXjQCjF
    client-secret: AgCSXx055+wPexm82zq4ZcC+ChZLW2fgXTYKY0rKTnAWgpelT6P+KUG4rQOxIhMUptgj6r7pfqaa1FW0u1Y02C/l0pE+KDfIIgYeYYL1UCBNU+7tfpQd4LqyrI0ljHoB1IqtmBP+ItnwfViVmbUhCw/Lo55JWMDSpYuoZAaYHdvl6IIzoR04sZeFqpf58y2/cB695Mu5dRwanMli0NCfF04SuoBodpRN7EoxATHcBNVSUDSSmpLdqjAw5TgFXbIx5RdmQV6FnTCOkmS0xoToVCk1ipddDvFB7hbALbZPBh7pfGwB6jPTZK4vV+8SsPFDLlNjELsty8+GNuVcXISUIfmBVPkt6oueTgP8UBLlYEANV88gIB/VSLVIv0bXPzhfd4XTytEUH1D0aDBa7a5GK1hgzaA7V458JWeYdWl9r9IVRhUwciJnT62F0pdqTLkCOcs0ZK2kSwe2x8UJqsXxZ7dyEn++uDYB/Zz9Mf/XsI/26snNW6iY9zUnkI4MEIxMmC3VMnvoeXpxXcIIq3kUU7o/dlvZxv8kqIMgtGdNZzvABsGnXxiA6Gslvw2nAPJgbdcXDkvbzhkFryDeL+4Hz44u2r4Dad7K2pXD5HE4mu4DuVjF3HaB/apvfda8OF2MfLivKOTUV4ok5UYNzgWiLroM1JAtwjnYd9Y07Hadb+PKPahEysLg1lesRNLO0UWJ3jajaI3Eve7SllyXd8xVDfp5qtRmua6tODDC4cLfWEv76g==
  template:
    metadata:
      name: grafana-oauth
      namespace: {{ .Release.Namespace }}
{{- end }}
