apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Release.Namespace }}
  name: opentelemetry-collector
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "namespaces", "nodes", "resourcequotas"]
    verbs: ["get", "list", "watch"]
